package com.swyp;

import com.google.cloud.firestore.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;

final class Bank {
  final Firestore db;
  final Nessie nessie;
  final ExecutorService jobs = Executors.newFixedThreadPool(2);

  Bank(Firestore db) {
    this(db, new Nessie());
  }

  Bank(Firestore db, Nessie nessie) {
    this.db = db;
    this.nessie = nessie;
  }

  DocumentReference user(String uid) {
    return db.collection("users").document(uid);
  }

  Map<String, Object> get(DocumentReference ref) throws Exception {
    var d = ref.get().get();
    return d.exists() ? d.getData() : Map.of();
  }

  Map<String, Object> initialize(String uid) throws Exception {
    var ref = user(uid);
    boolean generate =
        Boolean.TRUE.equals(get(db.document("config/app")).get("auto-generate-transactions"));
    db.runTransaction(
                tx -> {
                  if (tx.get(ref).get().exists()) return false;
                  tx.set(
                      ref,
                      Map.of(
                          "status",
                          "profile_required",
                          "simulated",
                          true,
                          "autoGenerated",
                          generate,
                          "createdAt",
                          FieldValue.serverTimestamp(),
                          "utilizationLimit",
                          0.30));
                  return generate;
                })
            .get();
    return get(ref);
  }

  private void startProvision(String uid, boolean history) {
    var ref = user(uid);
    jobs.submit(
          () -> {
            try {
              provision(uid, history);
            } catch (Exception e) {
              try {
                ref.update(
                        "status",
                        "needs_attention",
                        "message",
                        "Generation stopped. Inspect backend logs and Nessie before resuming; no"
                            + " automatic replay.")
                    .get();
              } catch (Exception ignored) {
              }
              System.err.println(
                  "Provisioning failed: " + e.getClass().getSimpleName() + ": " + e.getMessage());
            }
          });
  }

  void createCards(String uid) throws Exception {
    var ref = user(uid);
    db.runTransaction(
            tx -> {
              var d = tx.get(ref).get();
              if (!"ready".equals(d.getString("status")))
                throw new IllegalArgumentException("Account is busy");
              tx.update(ref, "status", "generating");
              return null;
            })
        .get();
    startProvision(uid, false);
  }

  void provision(String uid, boolean history) throws Exception {
    var ref = user(uid);
    if (!ref.collection("cards").get().get().isEmpty()) {
      ref.update("status", "ready").get();
      return;
    }
    String fullName = Objects.toString(get(ref).get("fullName"), "Swyp Member").trim();
    String[] nameParts = fullName.split("\\s+", 2);
    String customer =
        nessie.create(
            "/customers",
            Map.of(
                "first_name",
                nameParts[0],
                "last_name",
                nameParts.length > 1 ? nameParts[1] : "Member",
                "address",
                Map.of(
                    "street_number",
                    "1",
                    "street_name",
                    "Main Street",
                    "city",
                    "Blacksburg",
                    "state",
                    "VA",
                    "zip",
                    "24060")));
    ref.update(
            "nessieCustomerId",
            customer,
            "persona",
            history
                ? "Campus professional • groceries, dining, streaming, occasional travel"
                : "Blank demo wallet")
        .get();
    String merchant =
        nessie.create(
            "/merchants",
            Map.of(
                "name",
                "Swyp Demo Store " + uid,
                "category",
                "Other",
                "address",
                Map.of(
                    "street_number",
                    "1",
                    "street_name",
                    "Main Street",
                    "city",
                    "Blacksburg",
                    "state",
                    "VA",
                    "zip",
                    "24060"),
                "geocode",
                Map.of("lat", 37.2296, "lng", -80.4139)));
    ref.update("nessieMerchantId", merchant).get();
    var random = new Random(uid.hashCode());
    String[] products = {"savor", "quicksilver", "venture"};
    String[] names = {"Savor", "Quicksilver", "Venture"};
    for (int i = 0; i < products.length; i++) {
      String id = UUID.randomUUID().toString();
      long limit = (i + 1) * 300000L;
      String account =
          nessie.create(
              "/customers/" + customer + "/accounts",
              Map.of(
                  "type",
                  "Credit Card",
                  "nickname",
                  "Swyp " + names[i] + " " + id,
                  "rewards",
                  0,
                  "balance",
                  limit / 100));
      var card = ref.collection("cards").document(id);
      card.set(
              Map.of(
                  "id",
                  id,
                  "product",
                  products[i],
                  "name",
                  names[i],
                  "last4",
                  String.format("%04d", random.nextInt(10000)),
                  "limitCents",
                  limit,
                  "balanceCents",
                  0,
                  "nessieAccountId",
                  account,
                  "simulated",
                  true,
                  "annualFeeCents",
                  i == 2 ? 9500 : 0))
          .get();
      long currentBalance = 0;
      if (history) {
        for (int month = 18; month >= 0; month--) {
          LocalDate start = LocalDate.now(ZoneOffset.UTC).withDayOfMonth(1).minusMonths(month);
          long monthly = 0;
          for (int j = 0; j < 6; j++) {
            LocalDate date = start.plusDays(j == 0 ? 4 : random.nextInt(28));
            if (date.isAfter(LocalDate.now(ZoneOffset.UTC))) continue;
            long cents =
                j == 0 ? (i == 0 ? 1599 : i == 1 ? 6999 : 4999) : 1200 + random.nextInt(13000);
            String shop =
                j == 0
                    ? (i == 0 ? "Stream Plus" : i == 1 ? "Internet" : "Gym")
                    : (j % 2 == 0 ? "Kroger" : "Cafe");
            String category = j == 0 ? "bills" : (j % 2 == 0 ? "grocery" : "dining");
            String txId = "seed-" + id + "-" + date + "-" + j;
            String purchase =
                nessie.purchase(account, merchant, cents, date.toString(), txId + " " + shop);
            ref.collection("transactions")
                .document(txId)
                .set(
                    Map.of(
                        "id",
                        txId,
                        "cardId",
                        id,
                        "merchant",
                        shop,
                        "category",
                        category,
                        "amountCents",
                        cents,
                        "date",
                        date.toString(),
                        "nessiePurchaseId",
                        purchase,
                        "simulated",
                        true))
                .get();
            monthly += cents;
          }
          double util = monthly / (double) limit;
          ref.collection("statements")
              .document(id + "-" + start)
              .set(
                  Map.of(
                      "cardId",
                      id,
                      "date",
                      start.toString(),
                      "balanceCents",
                      monthly,
                      "utilization",
                      util,
                      "simulatedScore",
                      Math.max(300, Math.min(850, 780 - (int) (util * 250))),
                      "simulated",
                      true))
              .get();
          if (month == 0) currentBalance = monthly;
          else {
            // Nessie models an account balance; use deposits to replenish its demo spending pool.
            // Its current OpenAPI requires whole-dollar deposits. Record the rounded pool funding
            // separately from the exact synthetic credit repayment in Firestore.
            long fundingDollars = (monthly + 99) / 100;
            String deposit =
                nessie.create(
                    "/accounts/" + account + "/deposits",
                    Map.of(
                        "medium",
                        "balance",
                        "transaction_date",
                        start.withDayOfMonth(start.lengthOfMonth()).toString(),
                        "status",
                        "completed",
                        "amount",
                        fundingDollars,
                        "description",
                        "repay-" + id + "-" + start));
            ref.collection("repayments")
                .document(id + "-" + start)
                .set(
                    Map.of(
                        "cardId",
                        id,
                        "date",
                        start.withDayOfMonth(start.lengthOfMonth()).toString(),
                        "amountCents",
                        monthly,
                        "nessieFundingCents",
                        fundingDollars * 100,
                        "nessieDepositId",
                        deposit,
                        "simulated",
                        true))
                .get();
          }
        }
        String bill =
            nessie.create(
                "/accounts/" + account + "/bills",
                Map.of(
                    "status",
                    "recurring",
                    "payee",
                    i == 0 ? "Stream Plus" : i == 1 ? "Internet" : "Gym",
                    "nickname",
                    "Recurring demo bill",
                    "payment_amount",
                    i == 0 ? 15.99 : i == 1 ? 69.99 : 49.99,
                    "recurring_date",
                    5,
                    "payment_date",
                    LocalDate.now(ZoneOffset.UTC).plusMonths(1).withDayOfMonth(5).toString()));
        ref.collection("bills")
            .document(id)
            .set(
                Map.of(
                    "cardId",
                    id,
                    "nessieBillId",
                    bill,
                    "dayOfMonth",
                    5,
                    "amountCents",
                    i == 0 ? 1599 : i == 1 ? 6999 : 4999,
                    "merchant",
                    i == 0 ? "Stream Plus" : i == 1 ? "Internet" : "Gym"))
            .get();
      }
      card.update("balanceCents", currentBalance).get();
    }
    ref.update("status", "ready").get();
  }

  void settings(String uid, Map<String, Object> body) throws Exception {
    var updates = new HashMap<String, Object>();
    var account = get(user(uid));
    if (body.get("utilizationLimit") instanceof Number n) {
      double limit = n.doubleValue();
      if (!Double.isFinite(limit) || limit < 0.05 || limit > 0.80)
        throw new IllegalArgumentException("Invalid utilization target");
      updates.put("utilizationLimit", limit);
    }
    if (body.get("activatedOffer") instanceof String id) {
      if (!id.matches("[A-Za-z0-9_-]{1,100}")) throw new IllegalArgumentException("Invalid offer");
      updates.put("activatedOffers", FieldValue.arrayUnion(id));
    }
    boolean profileSubmitted = body.get("fullName") instanceof String;
    if (profileSubmitted) {
      String fullName = Json.str(body, "fullName").trim();
      String phone = Json.str(body, "phone").trim();
      String zip = Json.str(body, "homeZip").trim();
      long age = Json.num(body, "age");
      if (fullName.length() < 2
          || fullName.length() > 80
          || fullName.chars().anyMatch(c -> c < 32 || c == 127)
          || age < 18
          || age > 120
          || !phone.matches("[+0-9() .-]{7,20}")
          || !zip.matches("[0-9]{5}(-[0-9]{4})?"))
        throw new IllegalArgumentException("Check name, age, phone, and ZIP code");
      updates.put("fullName", fullName);
      updates.put("age", age);
      updates.put("phone", phone);
      updates.put("homeZip", zip);
      updates.put("profileUpdatedAt", FieldValue.serverTimestamp());
      if ("profile_required".equals(account.get("status")))
        updates.put(
            "status", Boolean.TRUE.equals(account.get("autoGenerated")) ? "generating" : "ready");
    }
    if (updates.isEmpty()) throw new IllegalArgumentException("No settings provided");
    user(uid).update(updates).get();
    if (profileSubmitted
        && "profile_required".equals(account.get("status"))
        && Boolean.TRUE.equals(account.get("autoGenerated"))) startProvision(uid, true);
  }

  void seedNearbyStores() throws Exception {
    var batch = db.batch();
    batch.set(
        db.collection("stores").document("kroger-university-city-blacksburg"),
        Map.of(
            "merchant", "Kroger",
            "name", "Kroger University City",
            "address", "903 University City Blvd, Blacksburg, VA 24060",
            "latitude", 37.2354614,
            "longitude", -80.4352291,
            "radiusMeters", 180));
    batch.set(
        db.collection("stores").document("walmart-christiansburg-1292"),
        Map.of(
            "merchant", "Walmart",
            "name", "Walmart Supercenter",
            "address", "2400 N Franklin St, Christiansburg, VA 24073",
            "latitude", 37.1605205,
            "longitude", -80.4257804,
            "radiusMeters", 220));
    batch.commit().get();
  }

  void registerKey(String uid, Map<String, Object> body) throws Exception {
    if (!"ready".equals(get(user(uid)).get("status")))
      throw new IllegalArgumentException("Wait for account setup to finish");
    String id = Json.str(body, "cardId"), key = Json.str(body, "publicKey");
    if (!id.matches("[A-Za-z0-9_-]{1,64}") || key.length() > 256)
      throw new IllegalArgumentException("Invalid credential");
    var parsed =
        java.security.KeyFactory.getInstance("EC")
            .generatePublic(
                new java.security.spec.X509EncodedKeySpec(Base64.getDecoder().decode(key)));
    if (!(parsed instanceof java.security.interfaces.ECPublicKey ec)
        || ec.getParams().getCurve().getField().getFieldSize() != 256)
      throw new IllegalArgumentException("Expected P-256 key");
    var card = user(uid).collection("cards").document(id);
    var existing = card.get().get();
    if (!existing.exists()) throw new IllegalArgumentException("Unknown card");
    if (Boolean.TRUE.equals(existing.getBoolean("posting")))
      throw new IllegalArgumentException("Resolve the current payment before preparing another");
    long now = Instant.now().getEpochSecond();
    var batch = db.batch();
    batch.update(
        card,
        Map.of("publicKey", key, "armedAt", now, "armedUntil", now + 120));
    batch.set(
        db.collection("credentials").document(id),
        Map.of("cardId", id, "uid", uid, "registeredAt", now));
    batch.commit().get();
  }

  Map<String, Object> processTerminal(Map<String, Object> proof) throws Exception {
    String cardId = Json.str(proof, "credentialId");
    if (!cardId.matches("[A-Za-z0-9_-]{1,64}"))
      throw new IllegalArgumentException("Invalid card");
    var credential = get(db.collection("credentials").document(cardId));
    String uid = Json.str(credential, "uid");
    if (!uid.matches("[A-Za-z0-9_-]{1,128}") || !cardId.equals(Json.str(credential, "cardId")))
      throw new IllegalArgumentException("Open Pay in Swyp and prepare this card again");
    DocumentReference ref = user(uid);
    DocumentReference cardRef = ref.collection("cards").document(cardId);
    String nonce = Json.str(proof, "nonce");
    var receipt = ref.collection("paymentRequests").document(nonce);
    long cents = Json.num(proof, "amountCents");
    long now = Instant.now().getEpochSecond();
    if (Math.abs(now - Json.num(proof, "timestamp")) > 120)
      throw new IllegalArgumentException("Payment request expired");

    boolean posted =
        db.runTransaction(
                tx -> {
                  var existing = tx.get(receipt).get();
                  if (existing.exists()) {
                    if ("posted".equals(existing.getString("status"))) return true;
                    throw new IllegalArgumentException("Payment already submitted");
                  }
                  var card = tx.get(cardRef).get();
                  PaymentProof.verify(proof, card.getString("publicKey"));
                  Long armedAt = card.getLong("armedAt"), armedUntil = card.getLong("armedUntil");
                  if (armedAt == null
                      || armedUntil == null
                      || Json.num(proof, "timestamp") < armedAt - 5
                      || Json.num(proof, "timestamp") > armedUntil)
                    throw new IllegalArgumentException("Open Pay in Swyp and prepare this card again");
                  if (Boolean.TRUE.equals(card.getBoolean("posting")))
                    throw new IllegalArgumentException("Card has an unresolved payment");
                  Long balance = card.getLong("balanceCents"), limit = card.getLong("limitCents");
                  if (balance == null || limit == null || balance + cents > limit)
                    throw new IllegalArgumentException("Card limit exceeded");
                  var request = new HashMap<String, Object>(proof);
                  request.put("status", "processing");
                  request.put("createdAt", FieldValue.serverTimestamp());
                  tx.create(receipt, request);
                  tx.update(cardRef, "posting", true, "armedUntil", 0L);
                  return false;
                })
            .get();
    if (posted) return get(receipt);

    var card = get(cardRef);
    try {
      String purchase =
          nessie.purchase(
              Json.str(card, "nessieAccountId"),
              Json.str(get(ref), "nessieMerchantId"),
              cents,
              LocalDate.now(ZoneOffset.UTC).toString(),
              "swyp:" + nonce);
      String merchant = Json.str(proof, "merchant");
      var batch = db.batch();
      batch.update(receipt, "status", "posted", "nessiePurchaseId", purchase);
      batch.update(cardRef, "balanceCents", FieldValue.increment(cents), "posting", false);
      batch.set(
          ref.collection("transactions").document(nonce),
          Map.of(
              "id", nonce,
              "cardId", cardId,
              "amountCents", cents,
              "merchant", merchant,
              "category", categoryFor(merchant),
              "date", LocalDate.now(ZoneOffset.UTC).toString(),
              "nessiePurchaseId", purchase,
              "simulated", true));
      batch.commit().get();
    } catch (Exception e) {
      receipt
          .update(
              "status",
              "needs_reconciliation",
              "message",
              "Nessie outcome may be unknown. Do not repeat this purchase.")
          .get();
      throw new IllegalStateException("Payment needs reconciliation; automatic retries disabled");
    }
    return get(receipt);
  }

  private static String categoryFor(String merchant) {
    String value = merchant.toLowerCase(Locale.ROOT);
    if (value.matches(".*(kroger|grocery|market|food lion|whole foods).*")) return "grocery";
    if (value.matches(".*(cafe|coffee|restaurant|grill|pizza|diner).*")) return "dining";
    if (value.matches(".*(gas|fuel|shell|exxon).*")) return "gas";
    if (value.matches(".*(hotel|airline|travel|uber|lyft).*")) return "travel";
    return "other";
  }

  Map<String, Object> process(String uid, String nonce) throws Exception {
    if (!nonce.matches("[A-Za-z0-9_-]{22}"))
      throw new IllegalArgumentException("Invalid request ID");
    var ref = user(uid);
    var receipt = ref.collection("paymentRequests").document(nonce);
    var p = get(receipt);
    if (p.isEmpty()) throw new IllegalArgumentException("Payment request not found");
    if ("posted".equals(p.get("status"))) return p;
    String cardId = Json.str(p, "credentialId");
    if (!cardId.matches("[A-Za-z0-9_-]{1,64}")) throw new IllegalArgumentException("Invalid card");
    var cardRef = ref.collection("cards").document(cardId);
    var card = get(cardRef);
    PaymentProof.verify(p, Json.str(card, "publicKey"));
    long now = Instant.now().getEpochSecond();
    // Firestore rules enforce freshness at creation. The device can process later when online.
    if (Json.num(p, "timestamp") > now + 30) throw new IllegalArgumentException("Future proof");
    long cents = Json.num(p, "amountCents");
    db.runTransaction(
            tx -> {
              var current = tx.get(receipt).get();
              var c = tx.get(cardRef).get();
              if (!"pending".equals(current.getString("status")))
                throw new IllegalArgumentException(
                    "Request already claimed; reconcile before retrying");
              if (Boolean.TRUE.equals(c.getBoolean("posting")))
                throw new IllegalArgumentException("Card has an unresolved payment");
              PaymentProof.verify(p, c.getString("publicKey"));
              if (Json.num(p, "timestamp") < c.getLong("armedAt") - 5
                  || Json.num(p, "timestamp") > c.getLong("armedUntil"))
                throw new IllegalArgumentException("No matching confirmed checkout");
              if (c.getLong("balanceCents") + cents > c.getLong("limitCents"))
                throw new IllegalArgumentException("Demo card limit exceeded");
              tx.update(receipt, "status", "processing");
              tx.update(cardRef, "posting", true, "armedUntil", 0L);
              return null;
            })
        .get();
    try {
      String purchase =
          nessie.purchase(
              Json.str(card, "nessieAccountId"),
              Json.str(get(ref), "nessieMerchantId"),
              cents,
              LocalDate.now(ZoneOffset.UTC).toString(),
              "swyp:" + nonce);
      var batch = db.batch();
      batch.update(receipt, "status", "posted", "nessiePurchaseId", purchase);
      batch.update(cardRef, "balanceCents", FieldValue.increment(cents), "posting", false);
      batch.set(
          ref.collection("transactions").document(nonce),
          Map.of(
              "id",
              nonce,
              "cardId",
              cardId,
              "amountCents",
              cents,
              "merchant",
              Json.str(p, "merchant"),
              "category",
              categoryFor(Json.str(p, "merchant")),
              "date",
              LocalDate.now(ZoneOffset.UTC).toString(),
              "nessiePurchaseId",
              purchase,
              "simulated",
              true));
      batch.commit().get();
    } catch (Exception e) {
      receipt
          .update(
              "status",
              "needs_reconciliation",
              "message",
              "Nessie outcome may be unknown. Do not repeat this purchase.")
          .get();
      throw new IllegalStateException("Payment needs reconciliation; automatic retries disabled");
    }
    return get(receipt);
  }
}
